name: ml4phys-course
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.6
  - pytest=7.1.3
  - numpy=1.23.3
  - scikit-learn=1.1.2
  - matplotlib=3.5.2
  - jupyter=1.0.0
  - jupyterlab=3.4.7
  - pytorch=1.12.1